CREATE TABLE users 
(
    id UUID PRIMARY KEY,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE farms
(
    id UUID PRIMARY KEY,
    name VARCHAR UNIQUE NOT NULL,
    lat DOUBLE PRECISION UNIQUE NOT NULL,
    long DOUBLE PRECISION UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE animals
(
    id UUID PRIMARY KEY,
    name VARCHAR NOT NULL,
    species VARCHAR NOT NULL,
    breed VARCHAR NOT NULL,
    birthdate DATE NOT NULL,
    gender VARCHAR NOT NULL,
    weight DOUBLE PRECISION NOT NULL,
    is_healthy BOOLEAN NOT NULL DEFAULT True,
    farm UUID REFERENCES farms(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE warehouse
(
    id UUID PRIMARY KEY,
    type VARCHAR(100) NOT NULL UNIQUE,
    quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
    cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE feed_arrival
(
    id UUID PRIMARY KEY,
    type VARCHAR(100) NOT NULL REFERENCES warehouse(type) ON DELETE CASCADE,
    quantity DOUBLE PRECISION NOT NULL,
    arrival_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes TEXT DEFAULT ''
);

CREATE TABLE medicine_arrival
(
    id UUID PRIMARY KEY,
    type VARCHAR(100) NOT NULL REFERENCES warehouse(type) ON DELETE CASCADE,
    quantity DOUBLE PRECISION NOT NULL,
    arrival_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes TEXT DEFAULT ''
);

CREATE TABLE feeding_record 
(
    id UUID PRIMARY KEY,
    type VARCHAR(100) NOT NULL REFERENCES warehouse(type) ON DELETE CASCADE,
    quantity DOUBLE PRECISION CHECK (quantity > 0),
    feeding_time TIMESTAMP NOT NULL,
    notes TEXT DEFAULT '',
    animal UUID REFERENCES animals(id) ON DELETE CASCADE
);

CREATE TABLE treatments
(
    id UUID PRIMARY KEY,
    animal UUID NOT NULL REFERENCES animals(id) ON DELETE CASCADE,
    medicine VARCHAR(100) NOT NULL REFERENCES warehouse(type) ON DELETE CASCADE,
    quantity DOUBLE PRECISION NOT NULL,
    treatment_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);